import 'dotenv/config';

import { PrismaPg } from '@prisma/adapter-pg';

import { PrismaClient } from '../src/generated/prisma/client';

interface SeedExercise {
  description: string;
  equipment: string;
  instructions: string;
  name: string;
  targetMuscleGroups: string[];
}

const databaseUrl = process.env.DATABASE_URL;

if (!databaseUrl) {
  throw new Error('DATABASE_URL is required to seed exercises.');
}

const exercises: SeedExercise[] = [
  // PECHO / UPPER BODY
  {
    name: 'Press de banca con barra',
    description: 'Press horizontal con barra en banco plano.',
    targetMuscleGroups: ['Pecho', 'Triceps', 'Hombros'],
    equipment: 'Barra',
    instructions: 'Baja la barra al pecho con control y empuja hacia arriba firmemente.',
  },
  {
    name: 'Press banca inclinado con mancuernas',
    description: 'Press en banco inclinado enfatizando la parte superior del pecho.',
    targetMuscleGroups: ['Pecho', 'Hombros', 'Triceps'],
    equipment: 'Mancuernas',
    instructions: 'Empuja las mancuernas manteniendo los codos a 45 grados del torso.',
  },
  {
    name: 'Aperturas en máquina Peck Deck o Contractora',
    description: 'Ejercicio de aislamiento para el pectoral en máquina contractora.',
    targetMuscleGroups: ['Pecho'],
    equipment: 'Maquinas',
    instructions: 'Junta los brazos frente al pecho apretando el pectoral en el centro.',
  },
  {
    name: 'Cruce de poleas',
    description: 'Aislamiento de pectoral utilizando la estación de poleas.',
    targetMuscleGroups: ['Pecho'],
    equipment: 'Maquinas',
    instructions: 'Cruza los agarres frente al cuerpo manteniendo un ligero doblez en los codos.',
  },
  {
    name: 'Press de banca inclinado con barra',
    description: 'Press con barra en banco inclinado para la porción clavicular del pecho.',
    targetMuscleGroups: ['Pecho', 'Hombros', 'Triceps'],
    equipment: 'Barra',
    instructions: 'Baja la barra a la parte alta del pecho y presiona verticalmente.',
  },
  {
    name: 'Press de banca con mancuernas',
    description: 'Press horizontal con mancuernas para mayor rango de movimiento.',
    targetMuscleGroups: ['Pecho', 'Triceps'],
    equipment: 'Mancuernas',
    instructions: 'Desciende las mancuernas a los lados del pecho y empuja hacia el centro.',
  },
  {
    name: 'Aperturas con mancuernas',
    description: 'Aperturas en banco plano con mancuernas.',
    targetMuscleGroups: ['Pecho'],
    equipment: 'Mancuernas',
    instructions: 'Abre los brazos lateralmente sintiendo el estiramiento en el pectoral.',
  },
  {
    name: 'Aperturas Inclinadas con mancuernas',
    description: 'Aperturas en banco inclinado con mancuernas.',
    targetMuscleGroups: ['Pecho'],
    equipment: 'Mancuernas',
    instructions: 'Mantén una curvatura fija en los codos al abrir y juntar las mancuernas.',
  },
  {
    name: 'Press de banca en máquina sentado',
    description: 'Press de pecho guiado en máquina sentada.',
    targetMuscleGroups: ['Pecho', 'Triceps'],
    equipment: 'Maquinas',
    instructions: 'Empuja los agarres hacia adelante extendiendo los brazos con control.',
  },
  {
    name: 'Press de banca declinado con barra',
    description: 'Press en banco declinado enfocando la porción inferior del pectoral.',
    targetMuscleGroups: ['Pecho', 'Triceps'],
    equipment: 'Barra',
    instructions: 'Baja la barra a la parte inferior del pecho y presiona hacia arriba.',
  },
  {
    name: 'Press de banca declinado con mancuernas',
    description: 'Press declinado con mancuernas.',
    targetMuscleGroups: ['Pecho', 'Triceps'],
    equipment: 'Mancuernas',
    instructions: 'Mantén la espalda apoyada firmemente en el banco declinado.',
  },
  {
    name: 'Flexiones',
    description: 'Flexiones de pecho con el peso corporal.',
    targetMuscleGroups: ['Pecho', 'Triceps', 'Abdominales'],
    equipment: 'Ninguno',
    instructions: 'Mantén el cuerpo recto y baja el pecho cerca del suelo.',
  },

  // ESPALDA / UPPER BODY
  {
    name: 'Remo con mancuerna a una mano',
    description: 'Remo unilateral apoándote en banco.',
    targetMuscleGroups: ['Espalda alta', 'Dorsal'],
    equipment: 'Mancuernas',
    instructions: 'Tracciona la mancuerna hacia la cadera manteniendo la espalda recta.',
  },
  {
    name: 'Jalón con agarre ancho',
    description: 'Jalón al pecho en polea alta con barra ancha.',
    targetMuscleGroups: ['Dorsal', 'Espalda alta'],
    equipment: 'Maquinas',
    instructions: 'Tracciona la barra hacia la parte superior del pecho.',
  },
  {
    name: 'Remo en máquina',
    description: 'Remo sentado con apoyo en máquina guiada.',
    targetMuscleGroups: ['Espalda alta', 'Dorsal'],
    equipment: 'Maquinas',
    instructions: 'Jala las manijas hacia el torso apretando las escápulas.',
  },
  {
    name: 'Jalón al pecho con agarre cerrado',
    description: 'Jalón al pecho utilizando agarre estrecho neutro o V-bar.',
    targetMuscleGroups: ['Dorsal', 'Biceps'],
    equipment: 'Maquinas',
    instructions: 'Lleva el agarre hacia el esternón enfocando la tracción en los dorsales.',
  },
  {
    name: 'Remo con barra',
    description: 'Remo inclinado con barra libre.',
    targetMuscleGroups: ['Espalda alta', 'Dorsal', 'Espalda baja'],
    equipment: 'Barra',
    instructions: 'Flexiona la cadera manteniéndola estable y jala la barra hacia el ombligo.',
  },
  {
    name: 'Jalón tras nuca',
    description: 'Jalón en polea alta por detrás de la cabeza.',
    targetMuscleGroups: ['Dorsal', 'Espalda alta'],
    equipment: 'Maquinas',
    instructions: 'Baja la barra suavemente por detrás de la nuca.',
  },
  {
    name: 'Jalón al pecho con agarre invertido',
    description: 'Jalón al pecho con palmas mirando hacia ti (supinado).',
    targetMuscleGroups: ['Dorsal', 'Biceps'],
    equipment: 'Maquinas',
    instructions: 'Tracciona hacia abajo involucrando dorsal ancho y bíceps.',
  },
  {
    name: 'Jalón en polea con cuerda',
    description: 'Jalón al pecho utilizando cuerda en polea alta.',
    targetMuscleGroups: ['Dorsal', 'Espalda alta'],
    equipment: 'Maquinas',
    instructions: 'Jala la cuerda hacia los lados del pecho al final del movimiento.',
  },
  {
    name: 'Remo en barra T',
    description: 'Remo en estación o barra en T.',
    targetMuscleGroups: ['Espalda alta', 'Dorsal'],
    equipment: 'Barra',
    instructions: 'Mantén el torso estable y acerca el peso al pecho.',
  },
  {
    name: 'Remo inclinado con barra con agarre supinado',
    description: 'Remo inclinado agarrando la barra con palmas hacia arriba.',
    targetMuscleGroups: ['Espalda alta', 'Dorsal', 'Biceps'],
    equipment: 'Barra',
    instructions: 'Mantén los codos pegados al cuerpo durante la tracción.',
  },
  {
    name: 'Elevaciones en barra fija',
    description: 'Dominadas con peso corporal agarre prono.',
    targetMuscleGroups: ['Dorsal', 'Espalda alta'],
    equipment: 'Ninguno',
    instructions: 'Eleva el cuerpo hasta que la barbilla supere la barra.',
  },
  {
    name: 'Elevaciones tras nuca en barra fija',
    description: 'Dominadas llevando la barra por detrás de la cabeza.',
    targetMuscleGroups: ['Dorsal', 'Espalda alta'],
    equipment: 'Ninguno',
    instructions: 'Sube con control llevando la nuca hacia la barra.',
  },
  {
    name: 'Elevaciones en barra fija con agarre supinado',
    description: 'Dominadas agarre supinado (Chin-ups).',
    targetMuscleGroups: ['Biceps', 'Dorsal'],
    equipment: 'Ninguno',
    instructions: 'Eleva el cuerpo enfatizando la flexión de los codos.',
  },
  {
    name: 'Jalón dorsal con brazos rectos',
    description: 'Pullover en polea alta con brazos extendidos.',
    targetMuscleGroups: ['Dorsal'],
    equipment: 'Maquinas',
    instructions: 'Empuja la barra hacia las piernas manteniendo codos rígidos.',
  },
  {
    name: 'Remo inclinado con mancuernas',
    description: 'Remo a dos manos inclinado con mancuernas.',
    targetMuscleGroups: ['Espalda alta', 'Dorsal'],
    equipment: 'Mancuernas',
    instructions: 'Eleva ambas mancuernas al costado del torso.',
  },
  {
    name: 'Pullover con mancuerna',
    description: 'Pullover tumbado en banco con mancuerna.',
    targetMuscleGroups: ['Dorsal', 'Pecho'],
    equipment: 'Mancuernas',
    instructions: 'Desciende la mancuerna por detrás de la cabeza y regresa al pecho.',
  },
  {
    name: 'Pullover con barra',
    description: 'Pullover en banco con barra.',
    targetMuscleGroups: ['Dorsal', 'Pecho'],
    equipment: 'Barra',
    instructions: 'Lleva la barra hacia atrás sobre la cabeza con codos semiflexionados.',
  },

  // HOMBROS Y TRAPECIO / UPPER BODY
  {
    name: 'Peso muerto con barra',
    description: 'Peso muerto convencional con barra libre.',
    targetMuscleGroups: ['Espalda baja', 'Femoral', 'Gluteos'],
    equipment: 'Barra',
    instructions: 'Levanta la barra extendiendo caderas y rodillas simultáneamente.',
  },
  {
    name: 'Peso muerto sumo con barra',
    description: 'Variante de peso muerto con pies separados y agarre estrecho.',
    targetMuscleGroups: ['Femoral', 'Gluteos', 'Adductor'],
    equipment: 'Barra',
    instructions: 'Mantén el torso erguido y empuja el suelo con los talones.',
  },
  {
    name: 'Peso muerto con barra hexagonal',
    description: 'Peso muerto con barra trampa (Trap bar).',
    targetMuscleGroups: ['Cuadriceps', 'Femoral', 'Espalda baja'],
    equipment: 'Barra',
    instructions: 'Agarra los mangos laterales y ponte de pie erguido.',
  },
  {
    name: 'Peso muerto con mancuernas',
    description: 'Peso muerto utilizando un par de mancuernas.',
    targetMuscleGroups: ['Femoral', 'Gluteos', 'Espalda baja'],
    equipment: 'Mancuernas',
    instructions: 'Baja las mancuernas cerca de las espinillas flexionando cadera.',
  },
  {
    name: 'Encogimiento de hombros con barra',
    description: 'Encogimientos para trapecio superior con barra.',
    targetMuscleGroups: ['Trapecio'],
    equipment: 'Barra',
    instructions: 'Eleva los hombros verticalmente hacia las orejas.',
  },
  {
    name: 'Encogimiento de hombros con mancuernas',
    description: 'Encogimientos con mancuernas a los lados.',
    targetMuscleGroups: ['Trapecio'],
    equipment: 'Mancuernas',
    instructions: 'Subes los hombros sin rotar los brazos.',
  },
  {
    name: 'Press de hombro con mancuernas',
    description: 'Press sentado o de pie para deltoides.',
    targetMuscleGroups: ['Hombros', 'Triceps'],
    equipment: 'Mancuernas',
    instructions: 'Empuja las mancuernas sobre la cabeza hasta casi tocar arriba.',
  },
  {
    name: 'Elevación lateral con mancuernas',
    description: 'Elevaciones laterales para deltoides lateral.',
    targetMuscleGroups: ['Hombros'],
    equipment: 'Mancuernas',
    instructions: 'Subes las mancuernas a los lados hasta la altura de los hombros.',
  },
  {
    name: 'Elevación frontal con mancuernas',
    description: 'Elevaciones frontales para deltoides anterior.',
    targetMuscleGroups: ['Hombros'],
    equipment: 'Mancuernas',
    instructions: 'Eleva las mancuernas hacia el frente a la altura de la vista.',
  },
  {
    name: 'Cruces inversos en polea alta',
    description: 'Cruces para deltoides posterior en cruz de poleas.',
    targetMuscleGroups: ['Hombros', 'Trapecio'],
    equipment: 'Maquinas',
    instructions: 'Abre los brazos hacia atrás a la altura de las orejas.',
  },
  {
    name: 'Press de hombros en Máquina Smith',
    description: 'Press militar guiado en máquina Smith.',
    targetMuscleGroups: ['Hombros', 'Triceps'],
    equipment: 'Maquinas',
    instructions: 'Presiona la barra verticalmente con control.',
  },
  {
    name: 'Remo alto con barra',
    description: 'Remo al mentón con barra para hombros y trapecio.',
    targetMuscleGroups: ['Hombros', 'Trapecio'],
    equipment: 'Barra',
    instructions: 'Jala la barra verticalmente pegada al cuerpo llevando los codos altos.',
  },
  {
    name: 'Elevaciones posteriores para hombros "Pájaro"',
    description: 'Elevaciones pájaro inclinado con mancuernas.',
    targetMuscleGroups: ['Hombros'],
    equipment: 'Mancuernas',
    instructions: 'Inclínate hacia adelante y abre los brazos lateralmente.',
  },
  {
    name: 'Elevación lateral con cable a una mano',
    description: 'Elevación lateral en polea baja.',
    targetMuscleGroups: ['Hombros'],
    equipment: 'Maquinas',
    instructions: 'Eleva la manija lateralmente manteniendo tensión continua.',
  },
  {
    name: 'Press Militar con mancuernas',
    description: 'Press militar de pie con mancuernas.',
    targetMuscleGroups: ['Hombros'],
    equipment: 'Mancuernas',
    instructions: 'Empuja las mancuernas sobre la cabeza manteniendo el core firme.',
  },
  {
    name: 'Press Militar',
    description: 'Press militar clásico con barra de pie.',
    targetMuscleGroups: ['Hombros', 'Triceps'],
    equipment: 'Barra',
    instructions: 'Presiona la barra desde la clavícula hacia arriba.',
  },
  {
    name: 'Elevaciones frontales con cable a una mano',
    description: 'Elevación frontal en polea baja.',
    targetMuscleGroups: ['Hombros'],
    equipment: 'Maquinas',
    instructions: 'Levanta el cable frontalmente con el brazo extendido.',
  },
  {
    name: 'Elevaciones frontales con barra',
    description: 'Elevación frontal agarre prono con barra.',
    targetMuscleGroups: ['Hombros'],
    equipment: 'Barra',
    instructions: 'Sube la barra frente a ti a la altura del pecho o los ojos.',
  },
  {
    name: 'Press militar sentado con barra',
    description: 'Press de hombro sentado con barra.',
    targetMuscleGroups: ['Hombros', 'Triceps'],
    equipment: 'Barra',
    instructions: 'Sentado en banco, empuja la barra por encima de la cabeza.',
  },
  {
    name: 'Press tras nuca sentado',
    description: 'Press de hombros bajando la barra tras la cabeza.',
    targetMuscleGroups: ['Hombros'],
    equipment: 'Barra',
    instructions: 'Controla el descenso justo detrás de la nuca y presiona.',
  },
  {
    name: 'Press militar de pie',
    description: 'Press militar con barra en posición erguida.',
    targetMuscleGroups: ['Hombros', 'Triceps'],
    equipment: 'Barra',
    instructions: 'Mantén abdominales apretados y presiona arriba.',
  },
  {
    name: 'Press militar de pie tras nuca',
    description: 'Press tras nuca de pie con barra.',
    targetMuscleGroups: ['Hombros'],
    equipment: 'Barra',
    instructions: 'Presiona sobre la cabeza partiendo desde detrás del cuello.',
  },
  {
    name: 'Elevación frontal con mancuernas alternas agarre neutro',
    description: 'Elevaciones frontales alternando brazos agarre martillo.',
    targetMuscleGroups: ['Hombros'],
    equipment: 'Mancuernas',
    instructions: 'Eleva un brazo a la vez hacia adelante.',
  },
  {
    name: 'Elevación frontal con un brazo en polea baja agarre neutro',
    description: 'Elevación frontal unilateral en cable.',
    targetMuscleGroups: ['Hombros'],
    equipment: 'Maquinas',
    instructions: 'Levanta la cuerda o manija frontalmente.',
  },
  {
    name: 'Elevación frontal con mancuerna a dos manos',
    description: 'Elevación frontal tomando una sola mancuerna con ambas manos.',
    targetMuscleGroups: ['Hombros'],
    equipment: 'Mancuernas',
    instructions: 'Sube la mancuerna sujetándola por los discos.',
  },

  // BICEPS Y ANTEBRAZO / UPPER BODY
  {
    name: 'Curl con barra',
    description: 'Curl de bíceps con barra recta.',
    targetMuscleGroups: ['Biceps'],
    equipment: 'Barra',
    instructions: 'Flexiona los codos subiendo la barra sin balancear la espalda.',
  },
  {
    name: 'Curl alterno con mancuernas',
    description: 'Curl de bíceps alternando brazos con mancuernas.',
    targetMuscleGroups: ['Biceps'],
    equipment: 'Mancuernas',
    instructions: 'Gira la muñeca al subir (supinación) y aprieta el bíceps.',
  },
  {
    name: 'Curl con cuerda en polea',
    description: 'Curl martillo en polea baja utilizando cuerda.',
    targetMuscleGroups: ['Biceps', 'Antebrazo'],
    equipment: 'Maquinas',
    instructions: 'Flexiona los codos separando la cuerda al final de la subida.',
  },
  {
    name: 'Curl con barra EZ',
    description: 'Curl de bíceps con barra Z para reducir tensión en muñecas.',
    targetMuscleGroups: ['Biceps'],
    equipment: 'Barra',
    instructions: 'Mantén los codos fijos a los lados del torso.',
  },
  {
    name: 'Curl de predicador con barra EZ',
    description: 'Curl en banco Scott con barra EZ.',
    targetMuscleGroups: ['Biceps'],
    equipment: 'Barra',
    instructions: 'Apoya los brazos en el cojín y flexiona la barra.',
  },
  {
    name: 'Curl alterno de martillo con mancuernas',
    description: 'Curl con palmas enfrentadas (martillo).',
    targetMuscleGroups: ['Biceps', 'Antebrazo'],
    equipment: 'Mancuernas',
    instructions: 'Subes las mancuernas de forma alterna en agarre neutro.',
  },
  {
    name: 'Curl inclinado con mancuernas',
    description: 'Curl en banco inclinado a 45 grados.',
    targetMuscleGroups: ['Biceps'],
    equipment: 'Mancuernas',
    instructions: 'Deja colgar los brazos e inicia la flexión sintiendo el estiramiento.',
  },
  {
    name: 'Curl concentrado con mancuernas',
    description: 'Curl sentado apoyando el codo en el muslo.',
    targetMuscleGroups: ['Biceps'],
    equipment: 'Mancuernas',
    instructions: 'Aísla el bíceps flexionando con control el brazo.',
  },
  {
    name: 'Curl de cable en polea baja a una mano',
    description: 'Curl unilateral en polea baja.',
    targetMuscleGroups: ['Biceps'],
    equipment: 'Maquinas',
    instructions: 'Tracciona el cable enfocado en un solo brazo.',
  },
  {
    name: 'Curl de cable con barra recta en polea baja',
    description: 'Curl de bíceps continuo en polea baja.',
    targetMuscleGroups: ['Biceps'],
    equipment: 'Maquinas',
    instructions: 'Flexiona la barra manteniendo tensión durante todo el recorrido.',
  },
  {
    name: 'Curl de cable en polea alta de pie',
    description: 'Curl doble bíceps en cruz de poleas altas.',
    targetMuscleGroups: ['Biceps'],
    equipment: 'Maquinas',
    instructions: 'Flexiona los codos trayendo los agarres hacia la cabeza.',
  },
  {
    name: 'Curl de muñeca con barra sentado',
    description: 'Ejercicio de flexores del antebrazo.',
    targetMuscleGroups: ['Antebrazo'],
    equipment: 'Barra',
    instructions: 'Apoya antebrazos en los muslos y flexiona la muñeca hacia arriba.',
  },
  {
    name: 'Extensión de muñeca con barra sentado',
    description: 'Ejercicio de extensores del antebrazo con agarre prono.',
    targetMuscleGroups: ['Antebrazo'],
    equipment: 'Barra',
    instructions: 'Eleva el reverso de las manos hacia el techo.',
  },
  {
    name: 'Curl de barra invertido',
    description: 'Curl de bíceps con palmas mirando hacia abajo.',
    targetMuscleGroups: ['Antebrazo', 'Biceps'],
    equipment: 'Barra',
    instructions: 'Flexiona la barra manteniendo el agarre prono.',
  },

  // TRICEPS / UPPER BODY
  {
    name: 'Extensión de tríceps tumbado',
    description: 'Press francés tumbado en banco plano.',
    targetMuscleGroups: ['Triceps'],
    equipment: 'Barra',
    instructions: 'Flexiona codos llevando la barra hacia la frente y extiéndelos.',
  },
  {
    name: 'Extensión de tríceps en polea',
    description: 'Jalón de tríceps en polea alta con barra recta o V.',
    targetMuscleGroups: ['Triceps'],
    equipment: 'Maquinas',
    instructions: 'Empuja la barra hacia abajo extendiendo por completo los codos.',
  },
  {
    name: 'Extensión de tríceps en polea con cuerda',
    description: 'Extensión en cable utilizando cuerda.',
    targetMuscleGroups: ['Triceps'],
    equipment: 'Maquinas',
    instructions: 'Separa los extremos de la cuerda al final de la extensión.',
  },
  {
    name: 'Extensión de tríceps con mancuernas por encima de la cabeza',
    description: 'Copa de tríceps a dos manos o una mano por detrás de la cabeza.',
    targetMuscleGroups: ['Triceps'],
    equipment: 'Mancuernas',
    instructions: 'Extiende los brazos verticalmente sobre la cabeza.',
  },
  {
    name: 'Press Banca con agarre cerrado',
    description: 'Press plano con manos juntas para enfatizar tríceps.',
    targetMuscleGroups: ['Triceps', 'Pecho'],
    equipment: 'Barra',
    instructions: 'Mantén los codos pegados al cuerpo al bajar la barra.',
  },
  {
    name: 'Patadas traseras',
    description: 'Patada de tríceps inclinado con mancuerna.',
    targetMuscleGroups: ['Triceps'],
    equipment: 'Mancuernas',
    instructions: 'Extiende el brazo hacia atrás de forma paralela al suelo.',
  },
  {
    name: 'Extensión de tríceps con cable de agarre inverso con barra',
    description: 'Extensión de tríceps en polea con agarre supinado.',
    targetMuscleGroups: ['Triceps'],
    equipment: 'Maquinas',
    instructions: 'Empuja hacia abajo sosteniendo la barra con palmas hacia arriba.',
  },
  {
    name: 'Extensión de tríceps con cable a una mano',
    description: 'Extensión unilateral de tríceps en polea.',
    targetMuscleGroups: ['Triceps'],
    equipment: 'Maquinas',
    instructions: 'Aísla el tríceps de un solo brazo extendiendo el codo.',
  },
  {
    name: 'Extensión de tríceps con cable a una mano con agarre supinado',
    description: 'Extensión unilateral con palmas hacia arriba.',
    targetMuscleGroups: ['Triceps'],
    equipment: 'Maquinas',
    instructions: 'Mantén el hombro estable y extiende el codo.',
  },
  {
    name: 'Extensión de tríceps con mancuernas tumbado',
    description: 'Press francés unilateral o bilateral con mancuernas.',
    targetMuscleGroups: ['Triceps'],
    equipment: 'Mancuernas',
    instructions: 'Baja las mancuernas hacia los lados de la cabeza y extiende.',
  },
  {
    name: 'Press francés sentado con barra',
    description: 'Press francés vertical sentado con barra EZ o recta.',
    targetMuscleGroups: ['Triceps'],
    equipment: 'Barra',
    instructions: 'Baja la barra por detrás de la cabeza y extiéndela arriba.',
  },
  {
    name: 'Fondos en banco',
    description: 'Fondos de tríceps apoyando manos en un banco plano.',
    targetMuscleGroups: ['Triceps'],
    equipment: 'Ninguno',
    instructions: 'Flexiona y extiende los codos con las piernas estiradas.',
  },
  {
    name: 'Fondos en barras paralelas',
    description: 'Fondos de tríceps/pecho en estación de paralelas.',
    targetMuscleGroups: ['Triceps', 'Pecho'],
    equipment: 'Ninguno',
    instructions: 'Mantén el cuerpo erguido para enfatizar tríceps al bajar y subir.',
  },

  // ABDOMINALES / UPPER BODY
  {
    name: 'Abdominales',
    description: 'Elevación de tronco con peso corporal.',
    targetMuscleGroups: ['Abdominales'],
    equipment: 'Ninguno',
    instructions: 'Flexiona el torso acercando las costillas a la cadera.',
  },
  {
    name: 'Crunch',
    description: 'Crunch abdominal tradicional.',
    targetMuscleGroups: ['Abdominales'],
    equipment: 'Ninguno',
    instructions: 'Eleva la parte superior de la espalda despegando los hombros.',
  },
  {
    name: 'Crunch oblicuo',
    description: 'Crunch con rotación para oblicuos.',
    targetMuscleGroups: ['Abdominales'],
    equipment: 'Ninguno',
    instructions: 'Lleva el codo hacia la rodilla contraria.',
  },
  {
    name: 'Abdominales en máquina',
    description: 'Crunch abdominal con resistencia guiada.',
    targetMuscleGroups: ['Abdominales'],
    equipment: 'Maquinas',
    instructions: 'Flexiona el tronco hacia adelante contra la resistencia de la máquina.',
  },
  {
    name: 'Abdominales con cuerda en polea alta',
    description: 'Crunch hincado con cuerda en polea alta.',
    targetMuscleGroups: ['Abdominales'],
    equipment: 'Maquinas',
    instructions: 'Lleva los codos hacia las rodillas apretando el abdomen.',
  },
  {
    name: 'Plancha',
    description: 'Plancha isométrica abdominal.',
    targetMuscleGroups: ['Abdominales'],
    equipment: 'Ninguno',
    instructions: 'Mantén el cuerpo alineado sobre antebrazos y puntas de pie.',
  },
  {
    name: 'Elevación de piernas',
    description: 'Elevación de piernas acostado o colgado.',
    targetMuscleGroups: ['Abdominales'],
    equipment: 'Ninguno',
    instructions: 'Eleva las piernas rectas sin arquear la espalda baja.',
  },
  {
    name: 'Encogimientos de rodillas para abdominales',
    description: 'Knee tucks para abdomen inferior.',
    targetMuscleGroups: ['Abdominales'],
    equipment: 'Ninguno',
    instructions: 'Acerca las rodillas al pecho en movimiento controlado.',
  },
  {
    name: 'Abdominales con brazos estirados',
    description: 'Crunch con los brazos totalmente extendidos hacia atrás.',
    targetMuscleGroups: ['Abdominales'],
    equipment: 'Ninguno',
    instructions: 'Mantén brazos rectos sobre la cabeza mientras elevas el tronco.',
  },
  {
    name: 'Plancha con flexión',
    description: 'Transición de plancha baja a plancha alta.',
    targetMuscleGroups: ['Abdominales', 'Pecho', 'Triceps'],
    equipment: 'Ninguno',
    instructions: 'Alterna apoyarte de antebrazos a palmas de las manos.',
  },

  // PIERNAS / LOWER BODY
  {
    name: 'Sentadilla',
    description: 'Sentadilla trasera libre con barra.',
    targetMuscleGroups: ['Cuadriceps', 'Gluteos'],
    equipment: 'Barra',
    instructions: 'Flexiona rodillas y cadera manteniendo el pecho erguido.',
  },
  {
    name: 'Prensa de piernas',
    description: 'Empuje de piernas en máquina incline u horizontal.',
    targetMuscleGroups: ['Cuadriceps', 'Gluteos'],
    equipment: 'Maquinas',
    instructions: 'Baja la plataforma hasta formar 90 grados en rodillas y presiona.',
  },
  {
    name: 'Extensión de piernas',
    description: 'Aislamiento de cuadriceps en máquina extensora.',
    targetMuscleGroups: ['Cuadriceps'],
    equipment: 'Maquinas',
    instructions: 'Extiende las piernas por completo y pausa arriba.',
  },
  {
    name: 'Zancada',
    description: 'Zancadas o estocadas dando pasos hacia adelante.',
    targetMuscleGroups: ['Cuadriceps', 'Gluteos'],
    equipment: 'Mancuernas',
    instructions: 'Da un paso largo y baja la rodilla posterior casi hasta el suelo.',
  },
  {
    name: 'Curl de pierna tumbado en máquina de femoral',
    description: 'Aislamiento de isquiotibiales en máquina tumbado.',
    targetMuscleGroups: ['Femoral'],
    equipment: 'Maquinas',
    instructions: 'Flexiona los talones hacia los glúteos.',
  },
  {
    name: 'Sentadilla Hack',
    description: 'Sentadilla en máquina Hack con inclinación.',
    targetMuscleGroups: ['Cuadriceps'],
    equipment: 'Maquinas',
    instructions: 'Apoya la espalda firmemente y desciende a la profundidad adecuada.',
  },
  {
    name: 'Curl de piernas sentado',
    description: 'Aislamiento de isquiotibiales en máquina sentado.',
    targetMuscleGroups: ['Femoral'],
    equipment: 'Maquinas',
    instructions: 'Empuja el rodillo hacia abajo y atrás.',
  },
  {
    name: 'Extensión a una pierna',
    description: 'Extensión de cuadriceps unilateral.',
    targetMuscleGroups: ['Cuadriceps'],
    equipment: 'Maquinas',
    instructions: 'Realiza la extensión concentrándote en una pierna a la vez.',
  },
  {
    name: 'Sentadilla frontal',
    description: 'Sentadilla cargando la barra sobre los deltoides anteriores.',
    targetMuscleGroups: ['Cuadriceps'],
    equipment: 'Barra',
    instructions: 'Mantén los codos altos y el torso muy vertical.',
  },
  {
    name: 'Peso muerto rumano (piernas rectas) con mancuernas',
    description: 'Hip hinge enfocado en estiramiento de femorales.',
    targetMuscleGroups: ['Femoral', 'Gluteos'],
    equipment: 'Mancuernas',
    instructions: 'Empuja la cadera hacia atrás manteniendo rodillas semirrígidas.',
  },
  {
    name: 'Peso muerto rumano (piernas rectas) con barra',
    description: 'RDL con barra libre.',
    targetMuscleGroups: ['Femoral', 'Gluteos'],
    equipment: 'Barra',
    instructions: 'Desciende la barra a lo largo de las piernas manteniendo la espalda neutra.',
  },
  {
    name: 'Sentadilla Goblet con mancuerna',
    description: 'Sentadilla sosteniendo la mancuerna vertical frente al pecho.',
    targetMuscleGroups: ['Cuadriceps', 'Gluteos'],
    equipment: 'Mancuernas',
    instructions: 'Sujeta la mancuerna al centro del pecho y realiza la sentadilla.',
  },
  {
    name: 'Sentadillas con propio peso',
    description: 'Sentadilla clásica sin carga adicional.',
    targetMuscleGroups: ['Cuadriceps'],
    equipment: 'Ninguno',
    instructions: 'Baja con control y extiende piernas por completo.',
  },
  {
    name: '1.5 repeticiones de sentadillas con propio peso',
    description: 'Sentadillas haciendo una repetición completa y media abajo.',
    targetMuscleGroups: ['Cuadriceps'],
    equipment: 'Ninguno',
    instructions: 'Baja del todo, sube hasta la mitad, baja de nuevo y sube completo.',
  },
  {
    name: 'Sentadillas con balón medicinal',
    description: 'Sentadillas abrazando o sosteniendo balón medicinal.',
    targetMuscleGroups: ['Cuadriceps', 'Full body'],
    equipment: 'Otros',
    instructions: 'Sostén el balón frente al cuerpo durante el descenso.',
  },
  {
    name: 'Sentadilla búlgara con barra',
    description: 'Sentadilla unilateral apoyando la pierna trasera en banco.',
    targetMuscleGroups: ['Cuadriceps', 'Gluteos'],
    equipment: 'Barra',
    instructions: 'Baja la cadera manteniendo el equilibrio sobre la pierna delantera.',
  },
  {
    name: 'Sentadilla búlgara con propio peso',
    description: 'Sentadilla búlgara sin equipo.',
    targetMuscleGroups: ['Cuadriceps', 'Gluteos'],
    equipment: 'Ninguno',
    instructions: 'Enfoca todo el trabajo en el cuadriceps y glúteo delantero.',
  },
  {
    name: 'Sentadilla con mini banda',
    description: 'Sentadilla colocándote una banda de resistencia en los muslos.',
    targetMuscleGroups: ['Gluteos', 'Cuadriceps'],
    equipment: 'Bandas de resistencia',
    instructions: 'Empuja las rodillas hacia afuera venciendo la tensión de la banda.',
  },
  {
    name: 'Sentadilla con salto',
    description: 'Sentadilla pliométrica explosiva.',
    targetMuscleGroups: ['Cuadriceps', 'Cardio'],
    equipment: 'Ninguno',
    instructions: 'Baja a la sentadilla y salta verticalmente al subir.',
  },
  {
    name: 'Sentadilla isométrica apoyado sobre la pared',
    description: 'Wall sit estático a 90 grados.',
    targetMuscleGroups: ['Cuadriceps'],
    equipment: 'Ninguno',
    instructions: 'Mantén la postura flexionada contra la pared por tiempo.',
  },
  {
    name: 'Peso muerto con balón medicinal',
    description: 'Bisagra de cadera levantando balón medicinal del suelo.',
    targetMuscleGroups: ['Femoral', 'Gluteos'],
    equipment: 'Otros',
    instructions: 'Mantén la espalda erguida al levantar el balón.',
  },
  {
    name: 'Peso muerto a una pierna',
    description: 'Single leg deadlift para equilibrio e isquiotibiales.',
    targetMuscleGroups: ['Femoral', 'Gluteos'],
    equipment: 'Mancuernas',
    instructions: 'Eleva la pierna trasera alineada con el torso mientras bajas la mancuerna.',
  },
  {
    name: 'Sentadilla sumo con kettlebell',
    description: 'Sentadilla amplia sosteniendo pesa rusa entre las piernas.',
    targetMuscleGroups: ['Cuadriceps', 'Adductor', 'Gluteos'],
    equipment: 'Kettlebell',
    instructions: 'Abre bien las piernas con puntas hacia afuera y desciende.',
  },
  {
    name: 'Ejercicio “buenos días” con barra',
    description: 'Inclinación de tronco con barra sobre la espalda superior.',
    targetMuscleGroups: ['Espalda baja', 'Femoral'],
    equipment: 'Barra',
    instructions: 'Flexiona la cadera manteniendo las piernas casi estiradas.',
  },

  // GLUTEOS Y CADERA / LOWER BODY
  {
    name: 'Puente con propio peso',
    description: 'Elevación de pelvis acostado boca arriba.',
    targetMuscleGroups: ['Gluteos', 'Femoral'],
    equipment: 'Ninguno',
    instructions: 'Aprieta los glúteos al elevar la cadera del suelo.',
  },
  {
    name: 'Puentes a una pierna',
    description: 'Puente de glúteo unilateral.',
    targetMuscleGroups: ['Gluteos', 'Femoral'],
    equipment: 'Ninguno',
    instructions: 'Empuja con un solo talón manteniendo la otra pierna elevada.',
  },
  {
    name: 'Puente con bandas',
    description: 'Puente de glúteo con banda en las rodillas.',
    targetMuscleGroups: ['Gluteos'],
    equipment: 'Bandas de resistencia',
    instructions: 'Mantén abducidas las rodillas mientras subes la pelvis.',
  },
  {
    name: 'Caminata de pato',
    description: 'Desplazamiento en postura baja de sentadilla.',
    targetMuscleGroups: ['Cuadriceps', 'Gluteos'],
    equipment: 'Ninguno',
    instructions: 'Camina hacia adelante manteniendo la flexión de rodillas constante.',
  },
  {
    name: 'Ejercicio Superman en cuadrupedia',
    description: 'Bird-dog sosteniendo apoyo en cuatro puntos.',
    targetMuscleGroups: ['Espalda baja', 'Gluteos'],
    equipment: 'Ninguno',
    instructions: 'Extiende brazo y pierna opuestos de forma paralela.',
  },
  {
    name: 'Los Groiners',
    description: 'Estiramiento dinámico y movilidad de cadera.',
    targetMuscleGroups: ['Full body', 'Cardio'],
    equipment: 'Ninguno',
    instructions: 'Lleva el pie al lado de la mano desde posición de plancha.',
  },
  {
    name: 'Hidrantes',
    description: 'Abducción de cadera en cuadrupedia (Fire hydrant).',
    targetMuscleGroups: ['Gluteos', 'Abductor'],
    equipment: 'Ninguno',
    instructions: 'Eleva la pierna doblada hacia el lateral.',
  },
  {
    name: 'Elevaciones de cadera con maquina Smith',
    description: 'Hip thrust apoyando la espalda en banco con barra Smith.',
    targetMuscleGroups: ['Gluteos'],
    equipment: 'Maquinas',
    instructions: 'Eleva la pelvis hasta bloquear los glúteos arriba.',
  },
  {
    name: 'Elevaciones de cadera con barra',
    description: 'Hip thrust pesado libre con barra.',
    targetMuscleGroups: ['Gluteos'],
    equipment: 'Barra',
    instructions: 'Empuja la barra hacia el techo desde el apoyo de la espalda.',
  },
  {
    name: 'Abducciones de cadera sentado con banda',
    description: 'Aperturas de piernas sentado con mini banda.',
    targetMuscleGroups: ['Abductor', 'Gluteos'],
    equipment: 'Bandas de resistencia',
    instructions: 'Separa las rodillas venciendo la tensión elástica.',
  },
  {
    name: 'Abducción de cadera con máquina de abducción de cadera',
    description: 'Apertura de piernas en máquina guiada.',
    targetMuscleGroups: ['Abductor'],
    equipment: 'Maquinas',
    instructions: 'Empuja las almohadillas hacia los lados abriendo las piernas.',
  },
  {
    name: 'Abducción con polea',
    description: 'Patada lateral de cadera en polea baja.',
    targetMuscleGroups: ['Abductor'],
    equipment: 'Maquinas',
    instructions: 'Eleva la pierna exterior separándola del cuerpo.',
  },
  {
    name: 'Elevaciones en posición de rana con propio peso',
    description: 'Frog pumps de glúteo juntando las plantas de los pies.',
    targetMuscleGroups: ['Gluteos'],
    equipment: 'Ninguno',
    instructions: 'Con rodillas abiertas y plantas unidas, sube la cadera.',
  },
  {
    name: 'Elevaciones cortas en posición de rana con maquina Smith',
    description: 'Frog pumps cortas con barra guiada.',
    targetMuscleGroups: ['Gluteos'],
    equipment: 'Maquinas',
    instructions: 'Realiza bombeos cortos aprentando el glúteo arriba.',
  },
  {
    name: 'Almejas laterales con banda',
    description: 'Clamshells en el suelo con banda elástica.',
    targetMuscleGroups: ['Abductor', 'Gluteos'],
    equipment: 'Bandas de resistencia',
    instructions: 'Acostado de lado, abre la rodilla superior sin mover los pies.',
  },
  {
    name: 'Levantamiento de pierna acostado de lado',
    description: 'Eleva la pierna superior totalmente extendida.',
    targetMuscleGroups: ['Abductor'],
    equipment: 'Ninguno',
    instructions: 'Sube la pierna en posición lateral controlando el descenso.',
  },
  {
    name: 'Elevaciones de bíceps femoral con máquina GHD',
    description: 'Glute ham raise en banco GHD.',
    targetMuscleGroups: ['Femoral', 'Gluteos'],
    equipment: 'Maquinas',
    instructions: 'Flexiona las rodillas subiendo el torso erguido.',
  },
  {
    name: 'Step Up con mancuernas',
    description: 'Subidas al cajón sosteniendo mancuernas.',
    targetMuscleGroups: ['Cuadriceps', 'Gluteos'],
    equipment: 'Mancuernas',
    instructions: 'Sube un pie al cajón y presiona con el talón.',
  },
  {
    name: 'Caminata lateral con minibanda',
    description: 'Pasos laterales en semi-sentadilla con banda.',
    targetMuscleGroups: ['Abductor', 'Gluteos'],
    equipment: 'Bandas de resistencia',
    instructions: 'Da pasos laterales manteniendo la tensión en la banda.',
  },
  {
    name: 'Elevaciones de rodilla',
    description: 'Elevaciones de rodillas alternas o salto.',
    targetMuscleGroups: ['Abdominales', 'Cardio'],
    equipment: 'Ninguno',
    instructions: 'Eleva dinámicamente las rodillas hacia la cadera.',
  },
  {
    name: 'Columpios con kettlebell',
    description: 'Kettlebell swing balancín de cadera.',
    targetMuscleGroups: ['Full body', 'Femoral', 'Gluteos'],
    equipment: 'Kettlebell',
    instructions: 'Impulsa la pesa con la bisagra de cadera hasta los hombros.',
  },
  {
    name: 'Contragolpe con cable',
    description: 'Glute kickback en polea baja.',
    targetMuscleGroups: ['Gluteos'],
    equipment: 'Maquinas',
    instructions: 'Extiende la pierna hacia atrás apretando el glúteo.',
  },
  {
    name: 'Patadas de burro',
    description: 'Donkey kick en cuadrupedia.',
    targetMuscleGroups: ['Gluteos'],
    equipment: 'Ninguno',
    instructions: 'Empuja la planta del pie hacia el techo doblando la rodilla 90 grados.',
  },
  {
    name: 'Elevaciones de cadera acostado lateralmente',
    description: 'Side plank hip dips.',
    targetMuscleGroups: ['Gluteos', 'Abductor'],
    equipment: 'Ninguno',
    instructions: 'Baja y sube la cadera en plancha lateral.',
  },
  {
    name: 'Sentadilla Posturas funcionales',
    description: 'Sentadilla profunda isométrica con trabajo de movilidad.',
    targetMuscleGroups: ['Cuadriceps', 'Full body'],
    equipment: 'Ninguno',
    instructions: 'Sostén la posición profunda de sentadilla abriendo caderas.',
  },
  {
    name: 'Elevación de gemelos sentado',
    description: 'Elevación de pantorrillas en máquina sentada (soleo).',
    targetMuscleGroups: ['Pantorrillas'],
    equipment: 'Maquinas',
    instructions: 'Eleva los talones con la máquina apoyada sobre los muslos.',
  },
  {
    name: 'Elevación de gemelos de pie',
    description: 'Elevación de talones de pie con barra o en escalón.',
    targetMuscleGroups: ['Pantorrillas'],
    equipment: 'Barra',
    instructions: 'Pónte en puntas de pie empujando lo más arriba posible.',
  },

  // OTROS Y CARDIO
  {
    name: 'Salto Rodillas al Pecho',
    description: 'Tuck jumps pliométrico de cardio intensivo.',
    targetMuscleGroups: ['Cardio', 'Full body'],
    equipment: 'Ninguno',
    instructions: 'Salta elevando ambas rodillas simultáneamente al pecho.',
  },
  {
    name: 'Burpees',
    description: 'Movimiento metabólico completo (flexión + salto).',
    targetMuscleGroups: ['Cardio', 'Full body'],
    equipment: 'Ninguno',
    instructions: 'Ve al suelo a realizar una flexión y salta explosivamente.',
  },
];

const adapter = new PrismaPg({ connectionString: databaseUrl });
const prisma = new PrismaClient({ adapter });

async function seed(): Promise<void> {
  console.log(`Seeding ${exercises.length} exercises...`);
  for (const exercise of exercises) {
    const existingExercise = await prisma.exercise.findFirst({
      where: { createdByUserId: null, name: exercise.name },
      select: { id: true },
    });
    if (!existingExercise) {
      await prisma.exercise.create({ data: exercise });
    } else {
      await prisma.exercise.update({
        where: { id: existingExercise.id },
        data: {
          description: exercise.description,
          equipment: exercise.equipment,
          instructions: exercise.instructions,
          targetMuscleGroups: exercise.targetMuscleGroups,
        },
      });
    }
  }
  console.log('Exercise seeding complete!');
}

seed()
  .then(() => prisma.$disconnect())
  .catch(async (error: unknown) => {
    await prisma.$disconnect();
    throw error;
  });
